name: build_Release

on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
         
      - name: Install Procursus
        uses: dhinakg/procursus-action@main
        with:
          packages: ldid fakeroot
         
      - name: Set t_name
        run: |
         t_name=$(TZ=UTC-8 date '+%s')
         echo "t_name=${t_name}" >> $GITHUB_ENV
    
      - name: Log t_name
        run: |
         echo ${{ env.t_name }}

      - name: Build tipa
        run: |
          sudo security import Exploits/fastPath/arm.pfx -k /Library/Keychains/System.keychain -P password -A
          make
          cp Fugu15/Fugu15.tipa 0Fugu15max.tipa
          mv Fugu15/Fugu15.tipa 0Fugu15max_${{ env.t_name }}.tipa
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: master
          prerelease: true
          body: tree/master
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          files: |
           *.tipa
